spring:
  application:
    name: ppob
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/nutech_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    expires-in-hours: 12