spring:
  application:
    name: ppob
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/nutech_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      resolve-lazily: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:my-super-long-jwt-secret-for-ppob-2025-10-31-abcdefghijkl}
    ttl-hours: ${JWT_TTL_HOURS:12}